// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPFXxQNWIlkk7twvpSLT-zQ-KINUksjbw',
    appId: '1:992357394768:web:208fa809ec1a46b94ee455',
    messagingSenderId: '992357394768',
    projectId: 'sample-4004d',
    authDomain: 'sample-4004d.firebaseapp.com',
    storageBucket: 'sample-4004d.appspot.com',
    measurementId: 'G-EL978HND28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbi-qaHUP6MTJ1ex7LHDK-6Dxx-ZOZiyQ',
    appId: '1:992357394768:android:b430b4348fe88edd4ee455',
    messagingSenderId: '992357394768',
    projectId: 'sample-4004d',
    storageBucket: 'sample-4004d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjFkvE5xk-In76RZxcjm_85AIN0UvBWKs',
    appId: '1:992357394768:ios:792bd0dc8f742d984ee455',
    messagingSenderId: '992357394768',
    projectId: 'sample-4004d',
    storageBucket: 'sample-4004d.appspot.com',
    iosBundleId: 'com.example.fgrynew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjFkvE5xk-In76RZxcjm_85AIN0UvBWKs',
    appId: '1:992357394768:ios:792bd0dc8f742d984ee455',
    messagingSenderId: '992357394768',
    projectId: 'sample-4004d',
    storageBucket: 'sample-4004d.appspot.com',
    iosBundleId: 'com.example.fgrynew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPFXxQNWIlkk7twvpSLT-zQ-KINUksjbw',
    appId: '1:992357394768:web:f668218e947d376c4ee455',
    messagingSenderId: '992357394768',
    projectId: 'sample-4004d',
    authDomain: 'sample-4004d.firebaseapp.com',
    storageBucket: 'sample-4004d.appspot.com',
    measurementId: 'G-7ZLWJ8K4C5',
  );
}
